language: objective-c
osx_image: xcode11
xcode_workspace: ReactorKitPractice.xcworkspace
xcode_sdk: iphonesimulator
xcode_scheme: ReactorKitPractice
xcode_destination: platform=iOS Simulator, OS=12.4, name=iPhone 11
before_install:
- gem install cocoapods-acknowledgements
- gem install cocoapods
- pod install --repo-update
script:
- set -o pipefail
- travis_retry xcodebuild -workspace ReactorKitPractice.xcworkspace -scheme ReactorKitPractice -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
